#!/usr/bin/env python3
"""Scaffold a new business-agnostic MKO plugin repository."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _sanitize_plugin_id(raw: str) -> str:
    value = (raw or "").strip().lower().replace("-", "_")
    if not value or not value.replace("_", "").isalnum():
        raise ValueError("plugin_id must be alphanumeric with optional '-' or '_'")
    return value


def create_scaffold(output_dir: Path, plugin_id: str, plugin_name: str, version: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_dir = output_dir / ".mko-plugin"
    playbooks_dir = output_dir / "playbooks"
    manifest_dir.mkdir(exist_ok=True)
    playbooks_dir.mkdir(exist_ok=True)

    manifest = {
        "id": plugin_id,
        "name": plugin_name,
        "version": version,
        "mko_plugin_api": "v1",
        "entrypoints": {
            "module": "plugin.py",
            "actions_factory": "get_actions",
            "health_factory": "collect_health",
        },
    }
    (manifest_dir / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    (output_dir / "plugin.py").write_text(
        "def collect_health():\n"
        "    return {\n"
        "        'status': 'unknown',\n"
        "        'checks': [],\n"
        "        'message': 'Implement plugin-specific health checks'\n"
        "    }\n\n"
        "def get_actions():\n"
        "    return [\n"
        "        {\n"
        "            'id': 'dry_run_health_check',\n"
        "            'name': 'Dry-Run Health Check',\n"
        "            'description': 'Runs a no-op safety playbook',\n"
        "            'type': 'ansible_playbook',\n"
        "            'playbook_path': 'playbooks/dry_run_health_check.yml',\n"
        "            'targets': [{'type': 'all_nodes'}]\n"
        "        }\n"
        "    ]\n",
        encoding="utf-8",
    )

    (playbooks_dir / "dry_run_health_check.yml").write_text(
        "---\n"
        "- name: Dry-run health check\n"
        "  hosts: all\n"
        "  gather_facts: no\n"
        "  tasks:\n"
        "    - name: Report plugin dry-run context\n"
        "      debug:\n"
        "        msg: \"MKO plugin dry-run health check\"\n",
        encoding="utf-8",
    )

    (output_dir / "README.md").write_text(
        f"# {plugin_name}\n\n"
        "Generated by `scripts/plugins/create_plugin_scaffold.py`.\n\n"
        "## Contract\n"
        "- Manifest: `.mko-plugin/plugin.json`\n"
        "- Entrypoint module: `plugin.py`\n"
        "- Action playbooks: `playbooks/*.yml`\n\n"
        "## Next Steps\n"
        "1. Implement `collect_health()` checks.\n"
        "2. Add guarded actions in `get_actions()`.\n"
        "3. Commit and pin commit SHA in MKO allowlists.\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a new MKO plugin scaffold")
    parser.add_argument("--output-dir", required=True, help="Directory to generate the plugin scaffold into")
    parser.add_argument("--plugin-id", required=True, help="Plugin ID (e.g. system_health)")
    parser.add_argument("--plugin-name", required=True, help="Human-readable plugin name")
    parser.add_argument("--version", default="0.1.0", help="Initial plugin version")
    args = parser.parse_args()

    plugin_id = _sanitize_plugin_id(args.plugin_id)
    output_dir = Path(args.output_dir).expanduser().resolve()
    if output_dir.exists() and any(output_dir.iterdir()):
        raise SystemExit(f"Refusing to scaffold into non-empty directory: {output_dir}")

    create_scaffold(output_dir=output_dir, plugin_id=plugin_id, plugin_name=args.plugin_name.strip(), version=args.version.strip())
    print(f"Scaffold created at: {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
