# MicroK8s Cluster Orchestrator - Default Configuration
# This is the default configuration file that will be used if no other config is found

# Database configuration
database:
  url: "sqlite:///data/orchestrator.db"
  echo: false

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/orchestrator.log"
  max_size: "10MB"
  backup_count: 5

# AI Assistant (RAG System) settings
ai_assistant:
  enabled: true  # Enable/disable AI assistant features
  rag_system:
    enabled: true  # Enable/disable RAG system
    data_dir: "data/local_rag"
    max_documents: 10000
    max_document_size: 50000
    retention_days: 365
    min_similarity: 0.1
    auto_learn: true  # Automatically learn from operations
  local_llm:
    enabled: false  # Enable/disable local LLM integration
    provider: "ollama"  # ollama, openai_local, or custom
    base_url: "http://localhost:11434"  # Ollama default URL
    api_key: ""  # API key if required
    model: "llama2"  # Default model to use
    timeout: 60  # Request timeout in seconds
    max_tokens: 2048  # Maximum tokens per response
    temperature: 0.7  # Response creativity (0.0-1.0)
    available_models: []  # List of available models (auto-populated)
  web_interface:
    enabled: true  # Enable/disable web chat interface
    show_in_nav: true  # Show assistant link in navigation
    allow_ansible_analysis: true  # Allow Ansible output analysis
    allow_health_insights: true  # Allow health insights generation
    allow_model_selection: true  # Allow users to select different models
    allow_multiple_chats: true  # Allow multiple chat sessions
    allow_operation_log_analysis: true  # Allow operation log analysis
  searchable_content:
    enabled: true  # Enable/disable searchable content features
    include_playbooks: true  # Include Ansible playbooks in search
    include_documentation: true  # Include documentation files in search
    include_operation_logs: true  # Include operation logs in search
    max_search_results: 50  # Maximum search results to return
  performance:
    max_concurrent_requests: 5
    response_timeout: 30  # seconds
    cache_responses: true
    cache_duration: 300  # seconds
  privacy:
    store_chat_history: true
    store_ansible_outputs: true
    anonymize_data: false  # Remove sensitive data from stored documents
    auto_cleanup: true
    cleanup_interval_days: 30

# SSH configuration
ssh:
  default_user: "ubuntu"
  default_port: 22
  key_size: 2048
  key_type: "rsa"

# Ansible configuration
ansible:
  inventory_file: "inventory.ini"
  playbook_dir: "ansible/playbooks"
  log_level: "INFO"
  timeout: 300

# Web interface configuration
web:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "your-secret-key-change-this"

# Cluster configuration
cluster:
  default_namespace: "default"
  enable_addons: true
  addons:
    - "dns"
    - "storage"
    - "metrics-server"

# Hardware monitoring
hardware:
  enabled: true
  collection_interval: 300  # seconds
  retention_days: 30

# UPS power management
ups:
  enabled: false
  nut_config_dir: "/etc/nut"
  shutdown_delay: 60  # seconds
  startup_delay: 30  # seconds

# Wake-on-LAN
wake_on_lan:
  enabled: true
  default_port: 9
  timeout: 5  # seconds
