---
# Default configuration for MicroK8s Cluster Orchestrator

# Database settings
database:
  path: "cluster_data.db"
  echo: false  # Set to true for SQL debugging

# Flask settings
flask:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "change-this-in-production"

# Ansible settings
ansible:
  config_file: "ansible/ansible.cfg"
  playbooks_dir: "ansible/playbooks"
  inventory_dir: "ansible/inventory"
  timeout: 300
  
# MicroK8s settings
microk8s:
  default_channel: "1.28/stable"
  default_addons:
    - dns
    - storage
    - ingress
  network:
    cluster_cidr: "10.1.0.0/16"
    service_cidr: "10.152.183.0/24"

# SSH settings
ssh:
  default_user: "ubuntu"
  default_port: 22
  connection_timeout: 30
  key_directory: "~/.ssh"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/orchestrator.log"
  max_size: "10MB"
  backup_count: 5

# Monitoring settings
monitoring:
  health_check_interval: 300  # seconds
  node_timeout: 60  # seconds
  cluster_timeout: 120  # seconds

# Security settings
security:
  encrypt_sensitive_data: true
  allowed_hosts: []  # Empty means all hosts allowed
  max_failed_operations: 5

# AI Assistant (RAG System) settings
ai_assistant:
  enabled: true  # Enable/disable AI assistant features
  rag_system:
    enabled: true  # Enable/disable RAG system
    data_dir: "data/local_rag"
    max_documents: 10000
    max_document_size: 50000
    retention_days: 365
    min_similarity: 0.1
    auto_learn: true  # Automatically learn from operations
  web_interface:
    enabled: true  # Enable/disable web chat interface
    show_in_nav: true  # Show assistant link in navigation
    allow_ansible_analysis: true  # Allow Ansible output analysis
    allow_health_insights: true  # Allow health insights generation
  performance:
    max_concurrent_requests: 5
    response_timeout: 30  # seconds
    cache_responses: true
    cache_duration: 300  # seconds
  privacy:
    store_chat_history: true
    store_ansible_outputs: true
    anonymize_data: false  # Remove sensitive data from stored documents
    auto_cleanup: true
    cleanup_interval_days: 30
