ansible:
  config_file: ansible/ansible.cfg
  inventory_dir: ansible/inventory
  playbooks_dir: ansible/playbooks
  timeout: 300
database:
  echo: false
  path: cluster_data.db
flask:
  debug: false
  host: 0.0.0.0
  port: 5000
  secret_key: change-this-in-production
logging:
  backup_count: 5
  file: logs/orchestrator.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 10MB
microk8s:
  default_addons:
  - dns
  - storage
  - ingress
  default_channel: 1.28/stable
  network:
    cluster_cidr: 10.1.0.0/16
    service_cidr: 10.152.183.0/24
monitoring:
  cluster_timeout: 120
  health_check_interval: 300
  node_timeout: 60
security:
  allowed_hosts: []
  encrypt_sensitive_data: true
  max_failed_operations: 5
ssh:
  connection_timeout: 30
  default_port: 22
  default_user: ubuntu
  key_directory: ~/.ssh
ai_assistant:
  enabled: true
  rag_system:
    enabled: true
    data_dir: data/local_rag
    max_documents: 10000
    max_document_size: 50000
    retention_days: 365
    min_similarity: 0.1
    auto_learn: true
  web_interface:
    enabled: true
    show_in_nav: true
    allow_ansible_analysis: true
    allow_health_insights: true
  performance:
    max_concurrent_requests: 5
    response_timeout: 30
    cache_responses: true
    cache_duration: 300
  privacy:
    store_chat_history: true
    store_ansible_outputs: true
    anonymize_data: false
    auto_cleanup: true
    cleanup_interval_days: 30
