apiVersion: v1
kind: ServiceAccount
metadata:
  name: mko
  namespace: orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mko-plugin-apply
  namespace: orchestrator
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mko-plugin-apply
  namespace: orchestrator
subjects:
  - kind: ServiceAccount
    name: mko
    namespace: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mko-plugin-apply

