---
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  - name: geerlingguy.docker
    version: ">=6.0.0"
  - name: geerlingguy.pip
    version: ">=2.2.0"
